# 审计消息处理器资源配置
processor_resources:
    - label: "processor_resource_audited"
      bloblang: |
       meta catalog   = "audited_log"
       root           = this
       root.message_type           = this.message_type.int32()
       root.id           		   = this.id.string()
       root.log_type              = match {
          this.exists("log_type") => this.log_type.string(),
          _ => "",
       }
       root.logged_at              = match {
          this.exists("logged_at") => this.logged_at.int64(),
          _ => 0.int64(),
       }
       root.logging_at              = match {
          this.exists("logging_at") => this.logging_at.int64(),
          _ => 0.int64(),
       }
       root.agent_id              = match {
          this.exists("agent_id") => this.agent_id.string(),
          _ => "",
       }
       root.agent_ip              = match {
          this.exists("agent_ip") => this.agent_ip.string(),
          _ => "",
       }
       root.agent_version              = match {
          this.exists("agent_version") => this.agent_version.string(),
          _ => "",
       }
       root.location              = match {
          this.exists("location") => this.location.string(),
          _ => "",
       }
       root.mac              = match {
          this.exists("mac") => this.mac.string(),
          _ => "",
       }
       root.group_id              = match {
          this.exists("group_id") => this.group_id.string(),
          _ => "",
       }
       root.group_name              = match {
          this.exists("group_name") => this.group_name.string(),
          _ => "",
       }
       root.hostname              = match {
          this.exists("hostname") => this.hostname.string(),
          _ => "",
       }
       root.principal_name              = match {
          this.exists("principal_name") => this.principal_name.string(),
          _ => "",
       }
       root.related_id              = match {
          this.exists("related_id") => this.related_id.string(),
          _ => "",
       }
       root.related_type              = match {
          this.exists("related_type") => this.related_type.string(),
          _ => "",
       }
       root.related_name              = match {
          this.exists("related_name") => this.related_name.string(),
          _ => "",
       }
       root.sup              = match {
          this.exists("sup") => this.sup.bool(),
          _ => false,
       }
       root.tenant_id              = match {
          this.exists("tenant_id") => this.tenant_id.string(),
          _ => "",
       }
       root.log_class              = match {
          this.exists("log_class") => this.log_class.int32(),
          _ => 0.int32(),
       }
       root.log_level              = match {
          this.exists("log_level") => this.log_level.int32(),
          _ => 0.int32(),
       }
       root.description              = match {
          this.exists("description") => this.description.string(),
          _ => "",
       }
       root.platform              = match {
          this.exists("platform") => this.platform.string(),
          _ => "",
       }
       root.attach_file_id              = match {
          this.exists("attach_file_id") => this.attach_file_id.string(),
          _ => "",
       }
       root.defense_type              = match {
          this.exists("defense_type") => this.defense_type.string(),
          _ => "",
       }
       root.errmsg              = match {
          this.exists("errmsg") => this.errmsg.string(),
          _ => "",
       }
       root.err              = match {
          this.exists("err") => this.err.int32(),
          _ => 0.int32(),
       }
       root.auto              = match {
          this.exists("auto") => this.auto.int32(),
          _ => 0.int32(),
       }
       root.file_num              = match {
          this.exists("file_num") => this.file_num.int64(),
          _ => 0.int64(),
       }
       root.parent_id              = match {
          this.exists("parent_id") => this.parent_id.string(),
          _ => "",
       }
       root.url              = match {
          this.exists("url") => this.url.string(),
          _ => "",
       }
       root.dstfn              = match {
          this.exists("dstfn") => this.dstfn.string(),
          _ => "",
       }
       root.product              = match {
          this.exists("product") => this.product.string(),
          _ => "",
       }
       root.new_product              = match {
          this.exists("new_product") => this.new_product.string(),
          _ => "",
       }
       root.asset_type              = match {
          this.exists("asset_type") => this.asset_type.string(),
          _ => "",
       }
       root.change_item              = match {
          this.exists("change_item") => this.change_item.string(),
          _ => "",
       }
       root.change_type              = match {
          this.exists("change_type") => this.change_type.string(),
          _ => "",
       }
       root.asset_category              = match {
          this.exists("asset_category") => this.asset_category.string(),
          _ => "",
       }
       root.original_configuration              = match {
          this.exists("original_configuration") => this.original_configuration.string(),
          _ => "",
       }
       root.new_configuration              = match {
          this.exists("new_configuration") => this.new_configuration.string(),
          _ => "",
       }
       root.virusdb_version              = match {
          this.exists("virusdb_version") => this.virusdb_version.string(),
          _ => "",
       }
       root.duration              = match {
          this.exists("duration") => this.duration.int64(),
          _ => 0.int64(),
       }
       root.start_at              = match {
          this.exists("start_at") => this.start_at.int64(),
          _ => 0.int64(),
       }
       root.end_at              = match {
          this.exists("end_at") => this.end_at.int64(),
          _ => 0.int64(),
       }
       root.virus_num              = match {
          this.exists("virus_num") => this.virus_num.int64(),
          _ => 0.int64(),
       }
       root.result_value              = match {
          this.exists("result_value") => this.result_value.string(),
          _ => "",
       }
       root.virus_name              = match {
          this.exists("virus_name") => this.virus_name.string(),
          _ => "",
       }
       root.virus_type              = match {
          this.exists("virus_type") => this.virus_type.string(),
          _ => "",
       }
       root.file_path              = match {
          this.exists("file_path") => this.file_path.string(),
          _ => "",
       }
       root.virus_path              = match {
          this.exists("virus_path") => this.virus_path.string(),
          _ => "",
       }
       root.result              = match {
          this.exists("result") => this.result.string(),
          _ => "",
       }
       root.isolation_result              = match {
          this.exists("isolation_result") => this.isolation_result.string(),
          _ => "",
       }
       root.reason              = match {
          this.exists("reason") => this.reason.string(),
          _ => "",
       }
       root.md5              = match {
          this.exists("md5") => this.md5.string(),
          _ => "",
       }
       root.sha1              = match {
          this.exists("sha1") => this.sha1.string(),
          _ => "",
       }
       root.sha256              = match {
          this.exists("sha256") => this.sha256.string(),
          _ => "",
       }
       root.pid              = match {
          this.exists("pid") => this.pid.string(),
          _ => "",
       }
       root.cmdline              = match {
          this.exists("cmdline") => this.cmdline.string(),
          _ => "",
       }
       root.proc_path              = match {
          this.exists("proc_path") => this.proc_path.string(),
          _ => "",
       }
       root.mon_type              = match {
          this.exists("mon_type") => this.mon_type.string(),
          _ => "",
       }
       root.probe_type              = match {
          this.exists("probe_type") => this.probe_type.string(),
          _ => "",
       }
       root.probe_ip              = match {
          this.exists("probe_ip") => this.probe_ip.string(),
          _ => "",
       }
       root.handle              = match {
          this.exists("handle") => this.handle.string(),
          _ => "",
       }
       root.network_name              = match {
          this.exists("network_name") => this.network_name.string(),
          _ => "",
       }
       root.network_card_mac              = match {
          this.exists("network_card_mac") => this.network_card_mac.string(),
          _ => "",
       }
       root.network_card_name              = match {
          this.exists("network_card_name") => this.network_card_name.string(),
          _ => "",
       }
       root.network_card_type              = match {
          this.exists("network_card_type") => this.network_card_type.string(),
          _ => "",
       }
       root.dev_name              = match {
          this.exists("dev_name") => this.dev_name.string(),
          _ => "",
       }
       root.dev_type              = match {
          this.exists("dev_type") => this.dev_type.string(),
          _ => "",
       }
       root.dev_id              = match {
          this.exists("dev_id") => this.dev_id.string(),
          _ => "",
       }
       root.action              = match {
          this.exists("action") => this.action.string(),
          _ => "",
       }
