# 终端连接日志消息处理器资源配置
processor_resources:
    - label: "processor_resource_sensitive_category_level"
      bloblang: |
       meta catalog   = "sensitive_category_level"
       root           = this
       root.message_type           = deleted()
