server_name: ngdlp
ip: 0.0.0.0
port: 8888
max_bytes: 100
nanomsguri: tcp://goms:15555
## absolute path
rpc_client_config: /home/topsec/config-map/server/rpc/client.yaml
rpcserverconf:
  name: ngdlp.rpc
  listenon: 0.0.0.0:8080
  ## timeout seconds
  timeout: 600
## pprof server
dev_server:
  enable: false
  listen_on: 0.0.0.0:6470
logger:
  level: error
  ## absolute path
  path: /home/topsec/data/logs/ngdlp
mongo_db:
  host: mongodb:27017
  username: root
  password: TopsecCdu_1130
cacheredis:
  - host: redis:6379
    type: node
    pass: TopsecCdu_1130
    db: 2
queue:
  driver: nats
  brokers:
    - nats:4222