# for process
processManagement:
   fork: false
net:
   bindIp: 0.0.0.0
   port: 27017
storage:
   dbPath: "/home/topsec/data/mongodb"
systemLog:
   verbosity: 2
   destination: file
   path: "/home/topsec/data/logs/mongodb/mongod.log"
   logAppend: true
storage:
   journal:
      enabled: true