# basic
# DNS cache 30s, 3s timeout
resolver 127.0.0.11 valid=30s;
sendfile      on;
tcp_nopush    on;
tcp_nodelay   on;
server_tokens off;
autoindex     off;

# timeout s
send_timeout          600;
keepalive_timeout     600;
proxy_read_timeout    600;
client_body_timeout   600;
client_header_timeout 600;

# buffer size
client_max_body_size          1024m;
client_body_buffer_size       300m;
client_header_buffer_size     10k;
large_client_header_buffers   2 10k;
server_names_hash_bucket_size 128;

# limit conn
#limit_conn_zone $binary_remote_addr zone=addr:5m;
#limit_conn addr 10000;
#limit_rate      1024m;

# fastcgi
fastcgi_buffer_size          128k;
fastcgi_buffers              8 128k;
fastcgi_busy_buffers_size    128k;
fastcgi_temp_file_write_size 128k;

# gzip
gzip              on;
gzip_vary         on;
gzip_static       on;
gzip_min_length   1k;
gzip_buffers      16 64k;
gzip_http_version 1.1;
gzip_comp_level   4;
gzip_types        application/javascript text/plain application/json application/x-javascript text/css application/xml text/javascript application/x-httpd-php image/jpeg image/gif image/png;
gzip_disable      "MSIE [1-6]\.";