# proxy pass
set $bff_proxy         http://bff:8888;
set $agentsvc_proxy    http://agentsvc:8888;
set $consumersvc_proxy http://consumersvc:8888;
set $ersvc_proxy       http://ersvc:8888;
set $licensesvc_proxy  http://licensesvc:8888;
set $managersvc_proxy  http://managersvc:8888;
set $systemsvc_proxy   http://systemsvc:8888;
set $upgradesvc_proxy  http://upgradesvc:8888;
set $downloader_proxy  http://upgradesvc:8000;
set $ngdlp_proxy       http://ngdlp:8888;
set $ngedr_proxy       http://ngedr:8888;
set $paddleocr_proxy   http://paddle-ocr:8866;

if ($request_method = 'OPTIONS') {
    return 200;
}

if ($query_string ~* "union.*select.*\(|concat.*\(") {
    return 400;
}

# host header verification, modify the corresponding IP, and uncomment.
#if ($http_host !~* ip|ip:443|ip:80|ip:8090|topsec.com.cn|topsec.com.cn:443|topsec.com.cn:80|topsec.com.cn:8090) {
#    return 403;
#}

# anti-hotlinking, modify the corresponding IP, and uncomment.
#location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$ {
#     valid_referers none blocked topsec.com.cn ip;
#     if ($invalid_referer) {
#         return 404;
#     }
#}

location ~ /\.ht {
    deny all;
}

location / {
    try_files $uri $uri/ /index.html?/$request_uri;
}

location /ngedrstatic/ {
    alias /home/topsec/data/web-dist/dist/;
    try_files $uri $uri/ /index.html?/$request_uri;
}

error_page 403 404         /404.html;
location = /404.html {
    root   /opt/bitnami/nginx/html;
}

error_page 500 502 503 504 /50x.html;
location = /50x.html {
    root   /opt/bitnami/nginx/html;
}