# Do not set it to auto, limit the number of processes, recommended to be half the CPU; requests_number = worker_processes * worker_connections
worker_processes  8;

events {
    multi_accept on;
    use epoll;
    worker_connections  1024;
}

http {
    default_type  application/octet-stream;
    log_format main '[$time_iso8601] $remote_addr $remote_user "$request" '
                    '$status $request_time $body_bytes_sent '
                    '"$http_referer" "$http_user_agent" "$http_x_forwarded_for" '
                    '"$upstream_addr $upstream_status $upstream_response_time"';
    # process /home/topsec/data/logs/web-nginx
    access_log /opt/bitnami/nginx/logs/access.log main;
    error_log  /opt/bitnami/nginx/logs/error.log;

    include conf.d/mime.types;
    include conf.d/basic.conf;
    include conf.d/header.conf;

    # access control, modify the corresponding IP, and uncomment.
    #allow ip;
    #deny all;

    server {
        server_name topsec.com.cn;
        listen 8443      ssl;
        listen [::]:8443 ssl;
        root  /home/topsec/data/web-dist/dist;

        # ssl verify
        ssl_certificate           /home/topsec/config-map/nginx/ca/web/server.crt;
        ssl_certificate_key       /home/topsec/config-map/nginx/ca/web/server.key;
        ssl_prefer_server_ciphers on;
        ssl_ciphers               TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
        ssl_protocols             TLSv1.2 TLSv1.3;
        ssl_session_cache         shared:SSL:10m;
        ssl_session_timeout       10m;

        include conf.d/proxy.conf;
        include custom/*.conf;

        location ~ /api/v1/consumer {
            proxy_pass $consumersvc_proxy;
        }

        location ~ /api/v1/er {
            proxy_pass $ersvc_proxy;
        }

        location ~ /api/v1/license {
            proxy_pass $licensesvc_proxy;
        }

        location ~ /api/v1/manager {
            proxy_pass $managersvc_proxy;
        }

        location ~ /api/v1/system {
            proxy_pass $systemsvc_proxy;
        }

        location ~ /api/v1/upgrade {
            proxy_pass $upgradesvc_proxy;
        }

        location ~ /api/v1/ngdlp {
            proxy_pass $ngdlp_proxy;
        }

        location ~ /api/v1/ngedr {
            proxy_pass $ngedr_proxy;
        }

        location ~ /api/v2/(system|auth) {
            proxy_pass $bff_proxy;
        }

        location ~ ^(/ngedrstatic)?/assets/newimg/public {
            rewrite ^/ngedrstatic(/assets/newimg/public/.*) $1 break;
            proxy_pass $bff_proxy;
        }
    }

    server {
        server_name topsec.com.cn;
        listen 8080;
        listen [::]:8080;
        root  /home/topsec/data/web-dist/downloader;

        include conf.d/proxy.conf;
        include custom/*.conf;

        location ~ /api/v1/downloader {
            proxy_pass $downloader_proxy;
        }
    }
}