server_name: managersvc
ip: 0.0.0.0
port: 8888
project: pingce
## absolute path
rpc_client_config: /home/topsec/config-map/server/rpc/client.yaml
rpcserverconf:
  name: managersvc.rpc
  listenon: 0.0.0.0:8080
  ## timeout seconds
  timeout: 30
## pprof server
dev_server:
  enable: false
  listen_on: 0.0.0.0:6470
logger:
  level: error
  ## absolute path
  path: /home/topsec/data/logs/managersvc
mongo_db:
  host: mongodb:27017
  username: root
  password: TopsecCdu_1130
cacheredis:
  - host: redis:7379
    type: node
    pass: TopsecCdu_1130
queue:
  driver: nats
  brokers:
    - nats:4222
  stream: aiop
business_logic_config:
  batch_delete_groups_notify: true
  client_additional_changed_notify: true
  client_info_config:
    dip_methods_of_list_client:
      - id:
          field_names:
            - sensitive_documents_count # 敏感文件统计个数
        dip_svc: ngdlp
    dip_methods_of_export_client_asset:
      - ngdlp
    excel_headers:
      - name: sensitive_documents_count
        display: 敏感文件个数
      - name: AIO
        display: AIO
      - name: DLP
        display: DLP
      - name: client_module_state_desc
        display: 状态描述
    default_column_orders:
      - name: sensitive_documents_count
        status: 0
        index: 1
      - name: AIO
        status: 0
        index: 2
      - name: DLP
        status: 0
        index: 3
      - name: client_module_state_desc
        status: 0
        index: 4
scanner:
  nmap_path:
  log_path: /home/topsec/data/logs/clientscanner
  queue:
    driver: nats
    brokers:
      - nats:4222
    stream: aiop