#fname表示功能模块名，调用agent.ReportLog时，服务端fname不存在则默认发送到服务端配置的消息队列，topic默认log_topic

[fname1]
#发送到nats，同理可换成服务端支持的消息队列
targets = nats
#默认发送到log_topic;多个用英文,分隔
topics = test1_topic,test2_topic

[fname2]
#同时发送到nats和benthos
targets = nats,benthos
#针对nats有效，默认log_topic
topics = test_topic
