# Do not set it to auto, limit the number of processes, recommended to be half the CPU; requests_number = worker_processes * worker_connections
worker_processes  8;

events {
    multi_accept on;
    use epoll;
    worker_connections  1024;
}

http {
    default_type  application/json;
    log_format main '[$time_iso8601] $remote_addr $remote_user "$request" '
                    '$status $request_time $body_bytes_sent '
                    '"$http_referer" "$http_user_agent" "$http_x_forwarded_for" '
                    '"$upstream_addr $upstream_status $upstream_response_time"';
    # process /home/topsec/data/logs/agent-nginx
    access_log /opt/bitnami/nginx/logs/access.log main;
    error_log  /opt/bitnami/nginx/logs/error.log;

    # qps limit
    #limit_req_zone $server_name zone=online_limit:10m rate=10r/s;

    include conf.d/mime.types;
    include conf.d/basic.conf;
    include conf.d/header.conf;

    # access control, modify the corresponding IP, and uncomment.
    #allow ip;
    #deny all;

    server {
        server_name topsec.com.cn;
        # http3
        #listen 8090 quic reuseport;
        listen 8090      ssl;
        listen [::]:8090 ssl;

        # ssl verify
        ssl_verify_client optional;
        ssl_client_certificate    /home/topsec/config-map/nginx/ca/agent/ca.crt;
        ssl_certificate           /home/topsec/config-map/nginx/ca/agent/server.crt;
        ssl_certificate_key       /home/topsec/config-map/nginx/ca/agent/server.key;
        ssl_prefer_server_ciphers on;
        ssl_ciphers               TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
        ssl_session_cache         shared:SSL:10m;
        ssl_session_timeout       10m;
        ssl_protocols             TLSv1.2 TLSv1.3;
        # http3
        #ssl_protocols    TLSv1.3;
        #add_header Alt-Svc 'h3=":8090"; ma=86400';

        include conf.d/proxy.conf;
        include custom/*.conf;

        # report component status, if the client reports too frequently, please uncomment the following.
        location ~* /component/_report {
            return 200;
        }

        # report process resource, if the client reports too frequently, please uncomment the following.
        location ~* /process_resource/_report {
            return 200;
        }

        #  report sentisitive info, if the client reports too frequently, please uncomment the following.
        #location ~* /sensitive_info/_report {
        #    return 200;
        #}

        location = /api/v1/agent/certificate/_info  {
            proxy_pass $agentsvc_proxy;
        }

        location = /api/v1/agent/ping {
            proxy_pass $agentsvc_proxy;
        }

        # online qps limit
        #location ~* /_online {
        #    limit_req zone=online_limit nodelay;
        #    limit_req_status 429;
        #    proxy_pass $agentsvc_proxy;
        #}

        location ~ /api/v1/agent {
            # open ssl verify, please uncomment the following.
            #if ($ssl_client_verify != SUCCESS) {
            #    return 401;
            #}
            proxy_pass $agentsvc_proxy;
        }

        location ~ /predict/ocr_system {
            proxy_pass $paddleocr_proxy;
        }
    }
}
